---@class LazyMenuAdapters
---@field plugin LazyMenuPluginAdapter
---@field which_key LazyMenuWhichKeyAdapter
---@field lsp LazyMenuLspAdapter
---@field keymaps LazyMenuKeymapsAdapter

---@class LazyMenuDomain
---@field plugin LazyMenuPluginDomain
---@field which_key LazyMenuWhichKeyDomain
---@field lsp LazyMenuLspDomain
---@field keymaps LazyMenuKeymapsDomain
