---@class LazyMenuAdapters
---@field plugin LazyMenuPluginAdapter
---@field values LazyMenuValuesAdapter
---@field lsp LazyMenuLspAdapter
---@field keymaps LazyMenuKeymapsAdapter

---@class LazyMenuDomain
---@field plugin LazyMenuPluginDomain
---@field values LazyMenuValuesDomain
---@field lsp LazyMenuLspDomain
---@field keymaps LazyMenuKeymapsDomain
